server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

client:
  ms-country:
    endpoint: http://localhost:8081


